spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ems
    username: root
    password: Crst#105243
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update